# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_NPY=111  CONDA_PY=27
    - CONDA_NPY=112  CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "WRz7JGNUi5tuqxXwH+YDPvgQydfIFISeM9YmQQOmR2jE3LsqSUs4ediQH/318rBO5mRdY02AFY3b+Gy0pRb1lPcxBVmNlMk1lsXuQHkmGQVYp3Dj6Y6dIhiOeALG9rwTUJVFk+g7vAgQE2UgA+DDTwoihjptSKMKy7vMwMQpe3SiJBTFaSyIiGg4E4Kmos0jLMX8HXwLSGo2Ci4fUih4rv24hAlDmiIMK9WgLPYbI1UHL8uxUsjo6TPoY9CXRE4P2qDT8X+7lOtmHAVTUkn7fPPTsAnZFLW9faCxi5BhMyUgjrEx7kwLotQ6bI10NLGsl1ccJJ3s4gvRmoKEmfPlaUqfvTlflrrpKcFjH+uhd8RSw88pYVu8Lo0miKXfiBbMhuN3TBPhPuJbjjEYz+6LJrtY5mwiIFjlgDYbXJJ7sgkuDxQN9xm+LGrA4M898kFkgxEF6FtpLWiFlBIsdFQ69yI9OvxtJ2q+KkWVPqJvrTMJZzLLgdQU0Uq1aYDXgRk3kOEwESGAJiQhpmxcGXjaNvqHklI0srjC22F1u+VXf2j3NkvNLiotYaxpxMfKdfoKsEZDtL8D+8wwkuHOUbibPsGSLjYsVIyvZKJgfCB/PS85GUt6RzsmO+klwfwHRbzcbUJBv0AO0yq4axomZ+PV70H4B8EHt8yKqr2TNr/WCvg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
