travis:
  secure:
    BINSTAR_TOKEN: E+Drbol33O2sLQUbf4nANL10lFfJOXNdvYqZnVUjUFR+XPXrqfwSjLSyoX73P1YkZJIwCHacFWhkuBjo64S+hoQPNrpLmo/P4LlDWpqot52v6ilQdjYf54eXOkZKnh87kyQjToSCI8fA9i9dhHDuuHqPe13UQxCFWC0Uw0v7+tcSxT3SzBjapMdkSP6qqN2sEyExE0JX+WxZ9cAyriBsFWGi4WTmMsJvvtGKeT1CxPEynXRgXPvA7+/7x0w+25n5NKSYjcBuuUVMGXWaz6O5OVu4O4++Z3T+fIfhYB0KzhEr/rD3diixB7PocgzDnPfiDQQwaKOm1SpKXPaKUci3m543wWwMEBYDRbDW7ckNEsus4JY7ronvUBkccDZO3WUfMMqUB7P7EdPFEpb1fYc5Vi7wWupqTk2zlzdreYRWLHws2VdDBfL7emOpAatrL3KQwuGR2Y2qjHhSMWwn+tq5LWqNipoJq05/SzVn7IvI/PML2ekyax/Q7KJESF5hV2WlqJ6C8w46r23/qG3CfVyaYAfF6tWfR3bGoMAIANiOuAInIIkD+/OSXBu9FEMU8o+I6tnbpt9j+nFQ4D/2WC3OaxUZvsfLWa0xue41lljskAN1kls+rsdpTwBDtUNZG5bicve34oKihXbGxl7C/LTjuZ3ZtQhfBNmc+LZNuHDstt8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
